name: Django CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python 3.1
    run: |
      wget https://www.python.org/ftp/python/3.1.5/Python-3.1.5.tgz
      tar xzf Python-3.1.5.tgz
      cd Python-3.1.5
      ./configure
      make
      sudo make install

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with Flake8
      run: |
        pip install flake8
        flake8 .

    - name: Run Tests and Collect Coverage
      run: |
        pip install coverage
        coverage run --source='.' manage.py test
        coverage report -m